### ISSUE TITLE
A few Suggestions

### ISSUE THREAD

**Issue by secfb** [3nock/sub3suite#3]
The tool is really good. I had two suggestions for you.

1. After detecting the subdomain, it would be great if live http/https detection was made. We should be able to see the status code while detecting live urls. (https://github.com/ScriptKid-Beta/WebBatchRequest like)
2. It would be great if you can take screenshots of live http/https after detecting them.
3. Will there be Mac OS X support?

**Comment by 3nock** [comment]
Thank you.

1. For the first suggestion, the URL Tool of Sub3 Suite has a similar functionality where you can see the status code and other info of live URLs.
![url](https://user-images.githubusercontent.com/82775800/163237770-9542f330-a3e4-41ff-a499-c63257d6ea68.png)

But I guess I could add an option for this to be possible for subdomains too. Thank you for the suggestion.

2. For the second suggestion about a screenshot tool for live pages, it is actually one of the feature I have been planning to introduce in the coming versions, for now though I have been caught up fixing bugs & making Sub3 Suite more stable, but it will be coming soon.

3. YES. the Mac OS X version will also be out soon before the end of this month, there are just some minor fixing soon to be finished.
