### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by jJit0** [3nock/sub3suite#4]
Hi,

I can't build the tool, I have an error:
```
make: *** No rule to make target 'src/enums/cidr/CIDREnum.ui', needed by 'ui_CIDREnum.h'.  Stop.
make: *** Waiting for unfinished jobs....
```
Although I followed exactly the build instructions!

Any idea ?

**Comment by 3nock** [comment]
are you building on windows/linux?

**Comment by jJit0** [comment]
linux, debian based distro

**Comment by 3nock** [comment]
thank you for raising this issue, it was due lower cases of the filenames in sub3suite/src/enums & sub3suite/src/tools. I just renamed them with appropriate cases.

try cloning the repo again and build.
