### ISSUE TITLE
Fix COMPILING.md information

### ISSUE THREAD

**Issue by D3vil0p3r** [3nock/sub3suite#7]
**Describe the bug**
I'm trying to compile the application by following [COMPILING.md](https://github.com/3nock/sub3suite/blob/main/COMPILING.md) document.

In the `.md` file, all the strings containing `qmake CONFIG+=release ../sub3suite/sub3suite` must be changed to `qmake CONFIG+=release ../sub3suite/sub3suite.pro`.

Furthermore, on "Run" section of the document, after the compilation, the bin file is not stored in `sub3suite/bin`. It is in `sub3suite/build` folder.

Could you also specify which relevant Qt libraries must be moved to the same folder of the binary file? I tried to move the binary field in different folders and it still starts correctly also without moving Qt libraries.

**Comment by 3nock** [comment]
Thank you for the important insight. i have now updated the [COMPILING.md](https://github.com/3nock/sub3suite/blob/main/COMPILING.md) to include the names of the relevant Qt5 libraries & fixed the typo in location of binaries in build folder.

I will leave this issue open for now if you have any further recommendations or questions.
